### ISSUE TITLE
request: add Mega 2560 PRO MINI support

### ISSUE THREAD

**Issue by itslemcy** [toyoshim/jvsio#3]
Hi, I am the guy on twitter that proposed the implementation of the Mega 2560 PRO MINI (@itslemcy).
Like this, we can achieve a two player configuration support since there are so many gpio's!
Thanks a lot!

**Comment by toyoshim** [comment]
Now that Mega2560 is supported by jvsio and iona, let me close this request.
If we need some additional supports for PRO MINI, please feel free to reopen this again.
